apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: asifpod3
  name: asifpod3
spec:
  volumes:
          - name: asifvol
            configMap:         # volume from configmap
             name: asifmapfile

  containers:
  - env: 
     - name: color
       valueFrom: 
        configMapKeyRef: 
         name: asifmap2
         key: x
    image: dockerashu/ckad:v2
    name: asifpod
    volumeMounts:
            - name: asifvol
              mountPath: /usr/share/nginx/html/
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
