apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: filepod4
  name: filepod4
spec:
  volumes:
          - name: asifvol
            configMap:         # volume from configmap
             name: asifmapfile

  containers:
   - image: nginx
     name: asifpod
     volumeMounts:
            - name: asifvol
              mountPath: /usr/share/nginx/html/
     resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
